# version: '3.9'

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@192.168.1.103:5432/test
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15.3-bookworm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  pgdata: {}

